force-app/main/default/objects/Worklog__c/Worklog__c.object-meta.xml
<CustomObject>
    <label>Worklog</label>
    <nameField>
        <displayFormat>WN-{00000}</displayFormat>
        <label>Worklog Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Worklog</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Worklog__c/fields/Drag_Table_Index__c.field-meta.xml
<CustomField>
    <fullName>Drag_Table_Index__c</fullName>
    <label>Drag Table Index</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Worklog__c/fields/Log_Detail__c.field-meta.xml
<CustomField>
    <fullName>Log_Detail__c</fullName>
    <label>Log Detail</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Worklog__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily Note</fullName>
            </value>
            <value>
                <fullName>Weekly Note</fullName>
            </value>
            <value>
                <fullName>Monthly Note</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WorklogController.cls
public with sharing class WorklogController {

    // @AuraEnabled(cacheable=true)
    // public static List<Worklog__c> getWorklogList() {
    //     return [SELECT Id, Name, Date__c, Type__c, Summary__c, Log_Detail__c FROM Worklog__c LIMIT 10];
    // }

    @AuraEnabled(cacheable=true)
    public static List<Worklog__c> findWorklogs(String searchKey) {
        if (String.isBlank(searchKey)) {
            //return new List<Worklog__c>();
            return [SELECT Id, Name, Date__c, Type__c, Summary__c, Log_Detail__c FROM Worklog__c LIMIT 10];
        }
        String key = '%' + searchKey + '%';
        return [SELECT Id, Name, Date__c, Type__c, Summary__c, Log_Detail__c FROM Worklog__c WHERE Summary__c LIKE :key  LIMIT 10];
    }

    @AuraEnabled(cacheable=true)
    public static List<Worklog__c> getAllWorklogs() {
        return [SELECT Id, Name, Date__c, Type__c, Summary__c, Log_Detail__c, Drag_Table_Index__c FROM Worklog__c ORDER BY Drag_Table_Index__c ASC];
        //return [SELECT Id, Name, Drag_Table_Index__c FROM Worklog__c ORDER BY Drag_Table_Index__c ASC];
    }

    @AuraEnabled(cacheable=true)
    public static string saveWorklogs(List<>){
        
    }

}